sudo: required
services:
    - docker
before_install:
    - docker build -t datolim/docker-react -f Dockerfile.dev .
scripts:
    - docker run -e CI=true datolim/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-147014502019"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
#  DockerReact-env.cnqhewskx9.us-east-2.elasticbeanstalk.com